// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTHfisj0KDs2m39-iQif6MWNciTM2CjNI',
    appId: '1:570800800281:web:583ee02ed6d9598838e088',
    messagingSenderId: '570800800281',
    projectId: 'proyek-penelitian-a04c7',
    authDomain: 'proyek-penelitian-a04c7.firebaseapp.com',
    databaseURL: 'https://proyek-penelitian-a04c7-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-penelitian-a04c7.appspot.com',
    measurementId: 'G-W7F9KBC7FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWonDlmdQhMZzgzSu52CNMK2CIUGomD-8',
    appId: '1:570800800281:android:29fe2afcc77cf26138e088',
    messagingSenderId: '570800800281',
    projectId: 'proyek-penelitian-a04c7',
    databaseURL: 'https://proyek-penelitian-a04c7-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-penelitian-a04c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXYMG43ukr10jqvMis2sDy2fJfh3DKwPY',
    appId: '1:570800800281:ios:9f449ad0c782f98e38e088',
    messagingSenderId: '570800800281',
    projectId: 'proyek-penelitian-a04c7',
    databaseURL: 'https://proyek-penelitian-a04c7-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-penelitian-a04c7.appspot.com',
    iosBundleId: 'com.example.proyekPenelitian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXYMG43ukr10jqvMis2sDy2fJfh3DKwPY',
    appId: '1:570800800281:ios:9f449ad0c782f98e38e088',
    messagingSenderId: '570800800281',
    projectId: 'proyek-penelitian-a04c7',
    databaseURL: 'https://proyek-penelitian-a04c7-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-penelitian-a04c7.appspot.com',
    iosBundleId: 'com.example.proyekPenelitian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTHfisj0KDs2m39-iQif6MWNciTM2CjNI',
    appId: '1:570800800281:web:72fc7e3d99d335a438e088',
    messagingSenderId: '570800800281',
    projectId: 'proyek-penelitian-a04c7',
    authDomain: 'proyek-penelitian-a04c7.firebaseapp.com',
    databaseURL: 'https://proyek-penelitian-a04c7-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-penelitian-a04c7.appspot.com',
    measurementId: 'G-0M6T8E4EWW',
  );
}
